Improvements to blast-bwa benchmark.

diff --git a/workflow/blast-bwa/setup-blast-bwa-benchmark b/workflow/blast-bwa/setup-blast-bwa-benchmark
--- a/workflow/blast-bwa/setup-blast-bwa-benchmark
+++ b/workflow/blast-bwa/setup-blast-bwa-benchmark
@@ -66,7 +66,23 @@ runscript="$scriptdir/run-blast-bwa-benchmark"
 #
 cat >$runscript <<'EOF'
 #!/bin/sh
-# needs to run in conda environment abyss
+# needs to run in conda environment blast-bwa
+
+nt=4
+
+if [ -z $1 ];
+then
+    	echo >&2 "warrning: missing argument 1 - default to 4 threads per BWA or BLAST run"
+        nt=4
+else
+        nt=$1
+fi
+
+if ! [[ $nt =~ ^[0-9]+$ ]];
+then
+    	echo >&2 "fatal error: incorrect format for argument 1. It should be an integer"
+        exit 1
+fi
 
 test -n "$INPUT_DATA_ROOT_DIR" || {
     echo >&2 "fatal error: missing environment variable INPUT_DATA_ROOT_DIR - source the top-level environment file"
@@ -124,7 +140,7 @@ for fastq in `ls $demultidir/*.fastq.gz | grep -v undetermined`; do
     i=$((i + 1))
     name=`echo $fastq | sed -e 's,^.*/\([^/]*\)$,\1,' -e 's,_.*$,,'`
     echo "echo \"bwa $name ($i of $nfiles)\"" >>$runscript
-    echo "bwa mem -t 1 -R \"@RG\\tID:$name\\tSM:$name\" \"\$datadir/Oar_v3.1.fa\" \"\$demultidir/$fastqbase\" 2>\$bwadir/$name.bwa.log | samtools view -b -S -u -T \$datadir/Oar_v3.1.fa -q 30 - | samtools sort -@ 1 - -o \$bwadir/$name.bam >\"\$bwadir/$name.out\" 2>\"\$bwadir/$name.out\"" >>$runscript
+    echo "bwa mem -t $nt -R \"@RG\\tID:$name\\tSM:$name\" \"\$datadir/Oar_v3.1.fa\" \"\$demultidir/$fastqbase\" 2>\$bwadir/$name.bwa.log | samtools view -b -S -u -T \$datadir/Oar_v3.1.fa -q 30 - | samtools sort -@ $nt - -o \$bwadir/$name.bam >\"\$bwadir/$name.out\" 2>\"\$bwadir/$name.out\"" >>$runscript
 done
 
 #
@@ -146,7 +162,7 @@ for fastq in `ls $demultidir/*.fastq.gz | grep -v undetermined`; do
     name=`echo $fastq | sed -e 's,^.*/\([^/]*\)$,\1,' -e 's,_.*$,,'`
     zcat "$demultidir/$fastqbase" | fastq_to_fasta -r -o "$demultidir/$name.fa"
     echo "echo \"blast $name ($i of $nfiles)\"" >>$runscript
-    echo "time blastn -task blastn -query \"\$demultidir/$name.fa\" -db nt -evalue 1.0e-10 -dust '20 64 1' -max_target_seqs 1 -outfmt '7 qseqid sseqid pident evalue staxids sscinames scomnames sskingdoms stitle' -out \"\$blastdir/$name.blast\" >\"\$blastdir/$name.out\" 2>\"\$blastdir/$name.err\"" >>$runscript
+    echo "time blastn -task blastn -num_threads $nt -query \"\$demultidir/$name.fa\" -db nt -evalue 1.0e-10 -dust '20 64 1' -max_target_seqs 1 -outfmt '7 qseqid sseqid pident evalue staxids sscinames scomnames sskingdoms stitle' -out \"\$blastdir/$name.blast\" >\"\$blastdir/$name.out\" 2>\"\$blastdir/$name.err\"" >>$runscript
 done
 
 chmod +x $runscript
